# Stage 1: Build static assets
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL
ARG VITE_WS_URL
ARG VITE_APP_CALENDAR_API
ARG VITE_CONTACT_API_BASE_URL
ARG VITE_NOTES_API_BASE_URL
ARG VITE_CALCULATOR_API_BASE_URL
ARG VITE_OPEN_METEO_API
ARG VITE_BIGDATA_CLOUD_API

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_WS_URL=$VITE_WS_URL
ENV VITE_APP_CALENDAR_API=$VITE_APP_CALENDAR_API
ENV VITE_CONTACT_API_BASE_URL=$VITE_CONTACT_API_BASE_URL
ENV VITE_NOTES_API_BASE_URL=$VITE_NOTES_API_BASE_URL
ENV VITE_CALCULATOR_API_BASE_URL=$VITE_CALCULATOR_API_BASE_URL
ENV VITE_OPEN_METEO_API=$VITE_OPEN_METEO_API
ENV VITE_BIGDATA_CLOUD_API=$VITE_BIGDATA_CLOUD_API

RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine AS runner

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
